In [2]:
import pandas as pd
import numpy as np

In [3]:
from sklearn import preprocessing

In [4]:
from sklearn import naive_bayes

In [5]:
data_awal = pd.read_excel("angkauji.xlsx")

In [6]:
x = data_awal.iloc[:, 1:-1]

In [7]:
y = data_awal.iloc[:, -1]

In [8]:
model = naive_bayes.CategoricalNB()

In [9]:
model.fit(x,y)

CategoricalNB()

In [56]:
x.values

array([[0, 0, 1, 1, 2, 0, 3, 1, 2, 1],
       [2, 1, 1, 1, 0, 0, 1, 0, 2, 1],
       [2, 0, 0, 1, 0, 0, 2, 1, 2, 1],
       [2, 0, 1, 1, 3, 1, 0, 2, 2, 1],
       [0, 0, 1, 1, 3, 1, 0, 0, 2, 1],
       [0, 0, 0, 1, 1, 1, 0, 0, 2, 1],
       [0, 0, 0, 0, 1, 1, 0, 0, 2, 1],
       [0, 0, 0, 1, 1, 1, 0, 0, 0, 0],
       [1, 0, 1, 1, 1, 1, 0, 0, 1, 0],
       [0, 0, 1, 1, 1, 1, 0, 2, 1, 0]], dtype=int64)

In [32]:
d = np.array([])

In [37]:
 def joint_log_likelihood(X):
    jll = np.zeros((X.shape[0], model.class_count_.shape[0]))
    for i in range(model.n_features_):
        indices = X[:, i]
        jll += model.feature_log_prob_[i][:, indices].T
    total_ll = jll + model.class_log_prior_
    print(jll)
    print(jll)
    return total_ll

In [59]:
jll = np.zeros((10,10))

In [57]:
jll = np.zeros((x.values.shape[0], model.class_count_.shape))
jll

TypeError: 'tuple' object cannot be interpreted as an integer

In [89]:
nilaiku = np.zeros((3,5))

In [91]:
nilaiku.shape

(3, 5)

In [74]:
nilaiku += 1

In [111]:
x.values[:, i]

array([1, 1, 0, 1, 1, 0, 0, 0, 1, 1], dtype=int64)

In [115]:
model.n_features_

10

In [122]:
nilaiku = np.zeros((10, 5))

In [123]:
nilaiku.shape

(10, 5)

In [124]:
for i in range(10):
    indices = x.values[:, i]
    nilaiku += model.feature_log_prob_[i][:, indices].T

In [125]:
nilaiku

array([[-10.09823163, -11.58584874,  -6.38450714,  -9.40508445,
         -8.71193727],
       [-10.79137881, -13.3776082 ,  -9.56256097,  -5.93934855,
         -8.71193727],
       [-10.09823163, -13.48296872,  -8.86941379,  -8.71193727,
         -5.93934855],
       [ -9.40508445,  -8.22547335,  -6.38450714,  -9.40508445,
         -9.40508445],
       [ -8.01879009,  -5.6997447 ,  -7.07765432,  -9.40508445,
        -10.09823163],
       [ -6.63249573,  -5.07113604,  -8.86941379, -10.09823163,
         -9.40508445],
       [ -5.93934855,  -6.86289551,  -9.96802607, -10.79137881,
        -10.09823163],
       [ -8.01879009,  -5.18891908, -11.06663836, -11.48452599,
        -10.79137881],
       [ -9.40508445,  -5.41206263, -10.66117325, -10.79137881,
        -11.48452599],
       [ -9.40508445,  -5.41206263,  -9.27487889, -11.48452599,
        -11.48452599]])

In [128]:
nilaiku.shape

(10, 5)

In [127]:
model.class_log_prior_.shape

(5,)

In [130]:
dijumlahkan = nilaiku + model.class_log_prior_

In [132]:
nilaiku

array([[-10.09823163, -11.58584874,  -6.38450714,  -9.40508445,
         -8.71193727],
       [-10.79137881, -13.3776082 ,  -9.56256097,  -5.93934855,
         -8.71193727],
       [-10.09823163, -13.48296872,  -8.86941379,  -8.71193727,
         -5.93934855],
       [ -9.40508445,  -8.22547335,  -6.38450714,  -9.40508445,
         -9.40508445],
       [ -8.01879009,  -5.6997447 ,  -7.07765432,  -9.40508445,
        -10.09823163],
       [ -6.63249573,  -5.07113604,  -8.86941379, -10.09823163,
         -9.40508445],
       [ -5.93934855,  -6.86289551,  -9.96802607, -10.79137881,
        -10.09823163],
       [ -8.01879009,  -5.18891908, -11.06663836, -11.48452599,
        -10.79137881],
       [ -9.40508445,  -5.41206263, -10.66117325, -10.79137881,
        -11.48452599],
       [ -9.40508445,  -5.41206263,  -9.27487889, -11.48452599,
        -11.48452599]])

In [131]:
dijumlahkan

array([[-12.40081672, -12.27899592,  -7.99394505, -11.70766954,
        -11.01452236],
       [-13.0939639 , -14.07075539, -11.17199888,  -8.24193364,
        -11.01452236],
       [-12.40081672, -14.1761159 , -10.4788517 , -11.01452236,
         -8.24193364],
       [-11.70766954,  -8.91862053,  -7.99394505, -11.70766954,
        -11.70766954],
       [-10.32137518,  -6.39289188,  -8.68709223, -11.70766954,
        -12.40081672],
       [ -8.93508082,  -5.76428323, -10.4788517 , -12.40081672,
        -11.70766954],
       [ -8.24193364,  -7.55604269, -11.57746399, -13.0939639 ,
        -12.40081672],
       [-10.32137518,  -5.88206626, -12.67607627, -13.78711108,
        -13.0939639 ],
       [-11.70766954,  -6.10520981, -12.27061117, -13.0939639 ,
        -13.78711108],
       [-11.70766954,  -6.10520981, -10.88431681, -13.78711108,
        -13.78711108]])

In [149]:
x8 = x.iloc[8:9 , :]

In [163]:
nilai_awal = np.zeros((3,5))

In [166]:
nilai_awal[1][3]

0.0

In [179]:
indi = x.values[:, 0]

In [184]:
indi

array([0, 2, 2, 2, 0, 0, 0, 0, 1, 0], dtype=int64)

In [197]:
model.feature_log_prob_ 

[array([[-0.69314718, -1.38629436, -1.38629436],
        [-0.47000363, -1.38629436, -2.07944154],
        [-0.91629073, -1.60943791, -0.91629073],
        [-1.38629436, -1.38629436, -0.69314718],
        [-1.38629436, -1.38629436, -0.69314718]]),
 array([[-0.40546511, -1.09861229],
        [-0.15415068, -1.94591015],
        [-0.28768207, -1.38629436],
        [-1.09861229, -0.40546511],
        [-0.40546511, -1.09861229]]),
 array([[-0.40546511, -1.09861229],
        [-0.84729786, -0.55961579],
        [-1.38629436, -0.28768207],
        [-1.09861229, -0.40546511],
        [-0.40546511, -1.09861229]]),
 array([[-0.40546511, -1.09861229],
        [-1.94591015, -0.15415068],
        [-1.38629436, -0.28768207],
        [-1.09861229, -0.40546511],
        [-1.09861229, -0.40546511]]),
 array([[-1.60943791, -0.91629073, -1.60943791, -1.60943791],
        [-2.19722458, -0.58778666, -2.19722458, -1.5040774 ],
        [-1.79175947, -1.79175947, -1.09861229, -1.09861229],
        [-0.91629073,

In [193]:
model.feature_log_prob_[0][:, indi].T.shape

(10, 5)

<center><span style="color: #0000ff; font-size: 30px;">Perhitungan Naive bayes di tahap akhir</span></center>

In [145]:
def joint_log_likelihood(X):
    jll = np.zeros((X.shape[0], model.class_count_.shape[0]))
    for i in range(model.n_features_):
        indices = X[:, i]
        jll += model.feature_log_prob_[i][:, indices].T
    total_ll = jll + model.class_log_prior_
    return total_ll

In [156]:
def prediksi(X):
    jll = joint_log_likelihood(X)
    return model.classes_[np.argmax(jll, axis=1)]

In [157]:
prediksi(x8.values)

array(['II'], dtype='<U3')

In [152]:
joint_log_likelihood(x8.values)

array([[-11.70766954,  -6.10520981, -12.27061117, -13.0939639 ,
        -13.78711108]])

In [95]:
nilaiku

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [81]:
nilaiku

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [61]:
for i in range(model.n_features_):
        indices = x.values[:, i]
        jll += model.feature_log_prob_[i][:, indices].T

ValueError: operands could not be broadcast together with shapes (10,10) (10,5) (10,10) 

In [62]:
jll.shape

(10, 10)

In [46]:
dd = x.values[:, 1]
dd

array([0, 1, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int64)

In [51]:
kkk = model.feature_log_prob_[1][: , dd].T
kkk

array([[-0.40546511, -0.15415068, -0.28768207, -1.09861229, -0.40546511],
       [-1.09861229, -1.94591015, -1.38629436, -0.40546511, -1.09861229],
       [-0.40546511, -0.15415068, -0.28768207, -1.09861229, -0.40546511],
       [-0.40546511, -0.15415068, -0.28768207, -1.09861229, -0.40546511],
       [-0.40546511, -0.15415068, -0.28768207, -1.09861229, -0.40546511],
       [-0.40546511, -0.15415068, -0.28768207, -1.09861229, -0.40546511],
       [-0.40546511, -0.15415068, -0.28768207, -1.09861229, -0.40546511],
       [-0.40546511, -0.15415068, -0.28768207, -1.09861229, -0.40546511],
       [-0.40546511, -0.15415068, -0.28768207, -1.09861229, -0.40546511],
       [-0.40546511, -0.15415068, -0.28768207, -1.09861229, -0.40546511]])

In [52]:
type(kkk)

numpy.ndarray

In [54]:
dd.shape

(10,)

In [53]:
kkk.shape

(10, 5)

In [34]:
data_test = x.iloc[0, :]

In [38]:
h = data_test.values.reshape(1, -1)

In [39]:
joint_log_likelihood(h)

[[-10.09823163 -11.58584874  -6.38450714  -9.40508445  -8.71193727]]
[[-10.09823163 -11.58584874  -6.38450714  -9.40508445  -8.71193727]]


array([[-12.40081672, -12.27899592,  -7.99394505, -11.70766954,
        -11.01452236]])

In [26]:
def predict(X):
        jll = joint_log_likelihood(X)
        return model.classes_[np.argmax(jll, axis=1)]

In [27]:
predict(h)

array(['III'], dtype='<U3')

In [140]:
model.classes_[np.argmax(dijumlahkan, axis=1)]

array(['III', 'IV', 'V', 'III', 'II', 'II', 'II', 'II', 'II', 'II'],
      dtype='<U3')

In [25]:
model.classes_

array(['I', 'II', 'III', 'IV', 'V'], dtype='<U3')

In [26]:
model.class_log_prior_

array([-2.30258509, -0.69314718, -1.60943791, -2.30258509, -2.30258509])

In [20]:
model.class_count_

array([1., 5., 2., 1., 1.])

In [27]:
model.feature_log_prob_

[array([[-0.69314718, -1.38629436, -1.38629436],
        [-0.47000363, -1.38629436, -2.07944154],
        [-0.91629073, -1.60943791, -0.91629073],
        [-1.38629436, -1.38629436, -0.69314718],
        [-1.38629436, -1.38629436, -0.69314718]]),
 array([[-0.40546511, -1.09861229],
        [-0.15415068, -1.94591015],
        [-0.28768207, -1.38629436],
        [-1.09861229, -0.40546511],
        [-0.40546511, -1.09861229]]),
 array([[-0.40546511, -1.09861229],
        [-0.84729786, -0.55961579],
        [-1.38629436, -0.28768207],
        [-1.09861229, -0.40546511],
        [-0.40546511, -1.09861229]]),
 array([[-0.40546511, -1.09861229],
        [-1.94591015, -0.15415068],
        [-1.38629436, -0.28768207],
        [-1.09861229, -0.40546511],
        [-1.09861229, -0.40546511]]),
 array([[-1.60943791, -0.91629073, -1.60943791, -1.60943791],
        [-2.19722458, -0.58778666, -2.19722458, -1.5040774 ],
        [-1.79175947, -1.79175947, -1.09861229, -1.09861229],
        [-0.91629073,

In [26]:
model.classes_

array(['I', 'II', 'III', 'IV', 'V'], dtype='<U3')

In [41]:
model.n_categories_

array([10,  3,  2,  2,  2,  4,  2,  4,  3,  3,  2])

In [10]:
model.category_count_

[array([[0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 1., 1., 0., 1., 1., 1.],
        [1., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.]]),
 array([[1., 0., 0.],
        [4., 1., 0.],
        [1., 0., 1.],
        [0., 0., 1.],
        [0., 0., 1.]]),
 array([[1., 0.],
        [5., 0.],
        [2., 0.],
        [0., 1.],
        [1., 0.]]),
 array([[1., 0.],
        [2., 3.],
        [0., 2.],
        [0., 1.],
        [1., 0.]]),
 array([[1., 0.],
        [0., 5.],
        [0., 2.],
        [0., 1.],
        [0., 1.]]),
 array([[0., 1., 0., 0.],
        [0., 4., 0., 1.],
        [0., 0., 1., 1.],
        [1., 0., 0., 0.],
        [1., 0., 0., 0.]]),
 array([[0., 1.],
        [0., 5.],
        [1., 1.],
        [1., 0.],
        [1., 0.]]),
 array([[1., 0., 0., 0.],
        [5., 0., 0., 0.],
        [1., 0., 0., 1.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.]]),
 arr

In [34]:
model.category_count_[0]

array([[0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 1., 0., 1., 1., 1.],
       [1., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.]])

In [29]:
pd.DataFrame(model.category_count_)

D:\python39\python38\venv\lib\site-packages\pandas\core\internals\construction.py:309: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  values = np.array([convert(v) for v in values])


0
0   [[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0,...
1   [[1.0, 0.0, 0.0], [4.0, 1.0, 0.0], [1.0, 0.0, ...
2   [[1.0, 0.0], [5.0, 0.0], [2.0, 0.0], [0.0, 1.0...
3   [[1.0, 0.0], [2.0, 3.0], [0.0, 2.0], [0.0, 1.0...
4   [[1.0, 0.0], [0.0, 5.0], [0.0, 2.0], [0.0, 1.0...
5   [[0.0, 1.0, 0.0, 0.0], [0.0, 4.0, 0.0, 1.0], [...
6   [[0.0, 1.0], [0.0, 5.0], [1.0, 1.0], [1.0, 0.0...
7   [[1.0, 0.0, 0.0, 0.0], [5.0, 0.0, 0.0, 0.0], [...
8   [[1.0, 0.0, 0.0], [4.0, 0.0, 1.0], [0.0, 1.0, ...
9   [[0.0, 0.0, 1.0], [1.0, 2.0, 2.0], [0.0, 0.0, ...
10  [[0.0, 1.0], [3.0, 2.0], [0.0, 2.0], [0.0, 1.0...

In [48]:
np.log(30)

3.4011973816621555

In [49]:
np.log(10)

2.302585092994046

In [50]:
np.log10(10)

1.0

In [51]:
model.class_log_prior_

array([-2.30258509, -0.69314718, -1.60943791, -2.30258509, -2.30258509])

In [67]:
model.get_params()

{'alpha': 1.0, 'class_prior': None, 'fit_prior': True, 'min_categories': None}

In [68]:
model.coef_

D:\python39\python38\venv\lib\site-packages\sklearn\utils\deprecation.py:101: FutureWarning: Attribute coef_ was deprecated in version 0.24 and will be removed in 1.1 (renaming of 0.26).
  warnings.warn(msg, category=FutureWarning)


[array([[-2.39789527, -2.39789527, -2.39789527, -2.39789527, -2.39789527,
         -2.39789527, -1.70474809, -2.39789527, -2.39789527, -2.39789527],
        [-2.7080502 , -2.7080502 , -2.7080502 , -2.7080502 , -2.01490302,
         -2.01490302, -2.7080502 , -2.01490302, -2.01490302, -2.01490302],
        [-1.79175947, -2.48490665, -2.48490665, -1.79175947, -2.48490665,
         -2.48490665, -2.48490665, -2.48490665, -2.48490665, -2.48490665],
        [-2.39789527, -1.70474809, -2.39789527, -2.39789527, -2.39789527,
         -2.39789527, -2.39789527, -2.39789527, -2.39789527, -2.39789527],
        [-2.39789527, -2.39789527, -1.70474809, -2.39789527, -2.39789527,
         -2.39789527, -2.39789527, -2.39789527, -2.39789527, -2.39789527]]),
 array([[-0.69314718, -1.38629436, -1.38629436],
        [-0.47000363, -1.38629436, -2.07944154],
        [-0.91629073, -1.60943791, -0.91629073],
        [-1.38629436, -1.38629436, -0.69314718],
        [-1.38629436, -1.38629436, -0.69314718]]),
 array

In [53]:
np.exp(-2.30258509)

0.10000000029940456

In [54]:
np.log(64)

4.1588830833596715

In [55]:
np.exp(4.1588830833596715)

63.99999999999998

In [56]:
np. (64)

1.806179973983887

In [76]:
model.feature_log_prob_

[array([[-2.39789527, -2.39789527, -2.39789527, -2.39789527, -2.39789527,
         -2.39789527, -1.70474809, -2.39789527, -2.39789527, -2.39789527],
        [-2.7080502 , -2.7080502 , -2.7080502 , -2.7080502 , -2.01490302,
         -2.01490302, -2.7080502 , -2.01490302, -2.01490302, -2.01490302],
        [-1.79175947, -2.48490665, -2.48490665, -1.79175947, -2.48490665,
         -2.48490665, -2.48490665, -2.48490665, -2.48490665, -2.48490665],
        [-2.39789527, -1.70474809, -2.39789527, -2.39789527, -2.39789527,
         -2.39789527, -2.39789527, -2.39789527, -2.39789527, -2.39789527],
        [-2.39789527, -2.39789527, -1.70474809, -2.39789527, -2.39789527,
         -2.39789527, -2.39789527, -2.39789527, -2.39789527, -2.39789527]]),
 array([[-0.69314718, -1.38629436, -1.38629436],
        [-0.47000363, -1.38629436, -2.07944154],
        [-0.91629073, -1.60943791, -0.91629073],
        [-1.38629436, -1.38629436, -0.69314718],
        [-1.38629436, -1.38629436, -0.69314718]]),
 array

In [88]:
model.classes_

array(['I', 'II', 'III', 'IV', 'V'], dtype='<U3')

In [86]:
model.class_count_

array([1., 5., 2., 1., 1.])

In [87]:
model.n_features_

11

In [92]:
model.n_features_

11

In [ ]:
 for i in range(self.n_features_):
            X_feature = X[:, i]
            self.category_count_[i] = _update_cat_count_dims(
                self.category_count_[i], self.n_categories_[i] - 1)
            _update_cat_count(X_feature, Y,
                              self.category_count_[i],
                              self.class_count_.shape[0])

In [ ]:
self.category_count_ = [np.zeros((n_effective_classes, 0))
                                for _ in range(n_features)]

In [9]:
model.category_count_

[array([[0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 1., 1., 0., 1., 1., 1.],
        [1., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.]]),
 array([[1., 0., 0.],
        [4., 1., 0.],
        [1., 0., 1.],
        [0., 0., 1.],
        [0., 0., 1.]]),
 array([[1., 0.],
        [5., 0.],
        [2., 0.],
        [0., 1.],
        [1., 0.]]),
 array([[1., 0.],
        [2., 3.],
        [0., 2.],
        [0., 1.],
        [1., 0.]]),
 array([[1., 0.],
        [0., 5.],
        [0., 2.],
        [0., 1.],
        [0., 1.]]),
 array([[0., 1., 0., 0.],
        [0., 4., 0., 1.],
        [0., 0., 1., 1.],
        [1., 0., 0., 0.],
        [1., 0., 0., 0.]]),
 array([[0., 1.],
        [0., 5.],
        [1., 1.],
        [1., 0.],
        [1., 0.]]),
 array([[1., 0., 0., 0.],
        [5., 0., 0., 0.],
        [1., 0., 0., 1.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.]]),
 arr

In [102]:
model.class_count_

array([1., 5., 2., 1., 1.])

In [107]:
model.predict_proba()

TypeError: predict_proba() missing 1 required positional argument: 'X'

In [100]:
model.n_categories_

array([10,  3,  2,  2,  2,  4,  2,  4,  3,  3,  2])

In [90]:
model.category_count_

[array([[0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 1., 1., 0., 1., 1., 1.],
        [1., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.]]),
 array([[1., 0., 0.],
        [4., 1., 0.],
        [1., 0., 1.],
        [0., 0., 1.],
        [0., 0., 1.]]),
 array([[1., 0.],
        [5., 0.],
        [2., 0.],
        [0., 1.],
        [1., 0.]]),
 array([[1., 0.],
        [2., 3.],
        [0., 2.],
        [0., 1.],
        [1., 0.]]),
 array([[1., 0.],
        [0., 5.],
        [0., 2.],
        [0., 1.],
        [0., 1.]]),
 array([[0., 1., 0., 0.],
        [0., 4., 0., 1.],
        [0., 0., 1., 1.],
        [1., 0., 0., 0.],
        [1., 0., 0., 0.]]),
 array([[0., 1.],
        [0., 5.],
        [1., 1.],
        [1., 0.],
        [1., 0.]]),
 array([[1., 0., 0., 0.],
        [5., 0., 0., 0.],
        [1., 0., 0., 1.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.]]),
 arr

In [97]:
model.n_features_

11

In [99]:
model.class_log_prior_

array([-2.30258509, -0.69314718, -1.60943791, -2.30258509, -2.30258509])

In [ ]:
for i in range(11):
    prnt()

In [80]:
def update_feature_log_prob(alpha):
    feature_log_prob = []
    for i in range(model.n_features_):
        smoothed_cat_count = model.category_count_[i] + alpha
        smoothed_class_count = smoothed_cat_count.sum(axis=1)
        feature_log_prob.append(
            np.log(smoothed_cat_count) -
            np.log(smoothed_class_count.reshape(-1, 1)))
#     self.feature_log_prob_ = feature_log_prob
    return feature_log_prob

0.6931471805599453

In [83]:
update_feature_log_prob(1.0)

[array([[-2.39789527, -2.39789527, -2.39789527, -2.39789527, -2.39789527,
         -2.39789527, -1.70474809, -2.39789527, -2.39789527, -2.39789527],
        [-2.7080502 , -2.7080502 , -2.7080502 , -2.7080502 , -2.01490302,
         -2.01490302, -2.7080502 , -2.01490302, -2.01490302, -2.01490302],
        [-1.79175947, -2.48490665, -2.48490665, -1.79175947, -2.48490665,
         -2.48490665, -2.48490665, -2.48490665, -2.48490665, -2.48490665],
        [-2.39789527, -1.70474809, -2.39789527, -2.39789527, -2.39789527,
         -2.39789527, -2.39789527, -2.39789527, -2.39789527, -2.39789527],
        [-2.39789527, -2.39789527, -1.70474809, -2.39789527, -2.39789527,
         -2.39789527, -2.39789527, -2.39789527, -2.39789527, -2.39789527]]),
 array([[-0.69314718, -1.38629436, -1.38629436],
        [-0.47000363, -1.38629436, -2.07944154],
        [-0.91629073, -1.60943791, -0.91629073],
        [-1.38629436, -1.38629436, -0.69314718],
        [-1.38629436, -1.38629436, -0.69314718]]),
 array

In [82]:
model.get_params()

{'alpha': 1.0, 'class_prior': None, 'fit_prior': True, 'min_categories': None}

In [108]:
x

Unnamed: 0  jenis_bantuan  jum_saudara_kandung  wilayah  kondisi_orang_tua  \
0           0              0                    0        1                  1   
1           1              2                    1        1                  1   
2           2              2                    0        0                  1   
3           3              2                    0        1                  1   
4           4              0                    0        1                  1   
5           5              0                    0        0                  1   
6           6              0                    0        0                  0   
7           7              0                    0        0                  1   
8           8              1                    0        1                  1   
9           9              0                    0        1                  1   

   pendidikan_ayah  pekerjaan_ayah  pendapatan_ayah  pendidikan_ibu  \
0                2               0                3               1   
1                0               0                1               0   
2                0               0                2               1   
3                3               1                0               2   
4                3               1                0               0   
5                1               1                0               0   
6                1               1                0               0   
7                1               1                0               0   
8                1               1                0               0   
9                1               1                0               2   

   pekerjaan_ibu  pendapatan_ibu  
0              2               1  
1              2               1  
2              2               1  
3              2               1  
4              2               1  
5              2               1  
6              2               1  
7              0               0  
8              1               0  
9              1               0

In [28]:
model.feature_log_prob_

[array([[-0.69314718, -1.38629436, -1.38629436],
        [-0.47000363, -1.38629436, -2.07944154],
        [-0.91629073, -1.60943791, -0.91629073],
        [-1.38629436, -1.38629436, -0.69314718],
        [-1.38629436, -1.38629436, -0.69314718]]),
 array([[-0.40546511, -1.09861229],
        [-0.15415068, -1.94591015],
        [-0.28768207, -1.38629436],
        [-1.09861229, -0.40546511],
        [-0.40546511, -1.09861229]]),
 array([[-0.40546511, -1.09861229],
        [-0.84729786, -0.55961579],
        [-1.38629436, -0.28768207],
        [-1.09861229, -0.40546511],
        [-0.40546511, -1.09861229]]),
 array([[-0.40546511, -1.09861229],
        [-1.94591015, -0.15415068],
        [-1.38629436, -0.28768207],
        [-1.09861229, -0.40546511],
        [-1.09861229, -0.40546511]]),
 array([[-1.60943791, -0.91629073, -1.60943791, -1.60943791],
        [-2.19722458, -0.58778666, -2.19722458, -1.5040774 ],
        [-1.79175947, -1.79175947, -1.09861229, -1.09861229],
        [-0.91629073,

In [112]:
model.class_log_prior_

array([-2.30258509, -0.69314718, -1.60943791, -2.30258509, -2.30258509])

In [30]:
def joint_log_likelihood(X):
    if not X.shape[1] == model.n_features_:
        raise ValueError("Expected input with %d features, got %d instead"
                         % (model.n_features_, X.shape[1]))
    jll = np.zeros((X.shape[0], model.class_count_))
    for i in range(model.n_features_):
        indices = X[:, i]
        jll += model.feature_log_prob_[i][:, indices].T
    total_ll = jll + model.class_log_prior_
    return total_ll

In [38]:
def likelihood(X):
#     if not X.shape[1] == model.n_features_:
#         raise ValueError("Expected input with %d features, got %d instead"
#                          % (model.n_features_, X.shape[1]))
    jll = np.zeros((X.shape[0], model.class_count_))
    for i in range(model.n_features_):
        indices = X[:, i]
        jll += model.feature_log_prob_[i][:, indices].T
    total_ll = jll + model.class_log_prior_
    return total_ll

TypeError: int() argument must be a string, a bytes-like object or a number, not 'DataFrame'

In [39]:
likelihood(x)

TypeError: only integer scalar arrays can be converted to a scalar index

In [37]:
model.class_count_

array([1., 5., 2., 1., 1.])

In [48]:
np.zeros(10, model.class_count_)

TypeError: Cannot construct a dtype from an array

In [36]:
np.zeros(x.shape[0], model_class_count_))

SyntaxError: unmatched ')' (<ipython-input-36-52af60cb3862>, line 1)

In [52]:
xvalues = x.values

In [54]:
model.class_count_

array([1., 5., 2., 1., 1.])

In [53]:
joint_log_likelihood(xvalues)

TypeError: only integer scalar arrays can be converted to a scalar index

In [91]:
model.class_count_

array([1., 5., 2., 1., 1.])

In [69]:
model.class_count_.shape[0]

5

In [92]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [79]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [87]:
xvalues

array([[0, 0, 1, 1, 2, 0, 3, 1, 2, 1],
       [2, 1, 1, 1, 0, 0, 1, 0, 2, 1],
       [2, 0, 0, 1, 0, 0, 2, 1, 2, 1],
       [2, 0, 1, 1, 3, 1, 0, 2, 2, 1],
       [0, 0, 1, 1, 3, 1, 0, 0, 2, 1],
       [0, 0, 0, 1, 1, 1, 0, 0, 2, 1],
       [0, 0, 0, 0, 1, 1, 0, 0, 2, 1],
       [0, 0, 0, 1, 1, 1, 0, 0, 0, 0],
       [1, 0, 1, 1, 1, 1, 0, 0, 1, 0],
       [0, 0, 1, 1, 1, 1, 0, 2, 1, 0]], dtype=int64)

In [74]:
np.zeros()

TypeError: zeros() missing required argument 'shape' (pos 1)

In [67]:
np.zeros(x.shape[0], model.class_count_.shape[0])

TypeError: Cannot interpret '5' as a data type

In [64]:
def okedong(X):
    if not X.shape[1] == model.n_features_:
        raise ValueError("Expected input with %d features, got %d instead"
                         % (model.n_features_, X.shape[1]))
    jll = np.zeros((X.shape[0], model.class_count_.shape[0]))
    for i in range(model.n_features_):
        indices = X[:, i]
        jll += model.feature_log_prob_[i][:, indices].T
    total_ll = jll + model.class_log_prior_
    return total_ll

In [101]:
b = [[]]

In [105]:
a = [[1,3,5], [3,5,6]]

In [106]:
b.append(a)

In [111]:
n = np.array([])

In [113]:
n.append(a)

AttributeError: 'numpy.ndarray' object has no attribute 'append'

In [115]:
np.array([])

array([], dtype=float64)

In [108]:
b[:, :]

TypeError: list indices must be integers or slices, not tuple

In [102]:
k = [[2,3,3]]

In [99]:
for i in range(3):
    k = [[]]
    b.append(i)

In [100]:
b

[[], 0, 1, 2]

In [90]:
model.class_log_prior_

array([-2.30258509, -0.69314718, -1.60943791, -2.30258509, -2.30258509])

In [93]:
np.exp(12.40081672)

242999.9994355874

In [88]:
okedong(xvalues)

array([[-12.40081672, -12.27899592,  -7.99394505, -11.70766954,
        -11.01452236],
       [-13.0939639 , -14.07075539, -11.17199888,  -8.24193364,
        -11.01452236],
       [-12.40081672, -14.1761159 , -10.4788517 , -11.01452236,
         -8.24193364],
       [-11.70766954,  -8.91862053,  -7.99394505, -11.70766954,
        -11.70766954],
       [-10.32137518,  -6.39289188,  -8.68709223, -11.70766954,
        -12.40081672],
       [ -8.93508082,  -5.76428323, -10.4788517 , -12.40081672,
        -11.70766954],
       [ -8.24193364,  -7.55604269, -11.57746399, -13.0939639 ,
        -12.40081672],
       [-10.32137518,  -5.88206626, -12.67607627, -13.78711108,
        -13.0939639 ],
       [-11.70766954,  -6.10520981, -12.27061117, -13.0939639 ,
        -13.78711108],
       [-11.70766954,  -6.10520981, -10.88431681, -13.78711108,
        -13.78711108]])